// <auto-generated>
// This code was generated by Maui.ColorResourcesGenerator
// Generated on: 2026-01-05 01:42:06
// Do not edit this file manually - changes will be overwritten!
// </auto-generated>

#nullable enable

namespace MyHome
{
    /// <summary>
    /// Exception thrown when a color resource cannot be found in the application resources.
    /// </summary>
    public class ColorResourceNotFoundException : System.Exception
    {
        /// <summary>
        /// Initializes a new instance of ColorResourceNotFoundException.
        /// </summary>
        /// <param name="colorKey">The key of the color resource that was not found.</param>
        public ColorResourceNotFoundException(string colorKey)
            : base($"Color resource '{colorKey}' not found in application resources. Ensure Colors.xaml is properly loaded.")
        {
            ColorKey = colorKey;
        }

        /// <summary>
        /// Gets the key of the color resource that was not found.
        /// </summary>
        public string ColorKey { get; }
    }

    /// <summary>
    /// Auto-generated fluent helper class for accessing color resources from Colors.xaml
    /// </summary>
    public static class AppColors
    {
        #region Standard Colors

        private static Microsoft.Maui.Graphics.Color? _backgroundDark;
        /// <summary>
        /// Color resource: BackgroundDark (#121212)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color BackgroundDark
        {
            get
            {
                if (_backgroundDark == null)
                {
                    _backgroundDark = Microsoft.Maui.Controls.Application.Current?.Resources["BackgroundDark"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("BackgroundDark");
                }
                return _backgroundDark;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _backgroundLight;
        /// <summary>
        /// Color resource: BackgroundLight (#FFFFFF)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color BackgroundLight
        {
            get
            {
                if (_backgroundLight == null)
                {
                    _backgroundLight = Microsoft.Maui.Controls.Application.Current?.Resources["BackgroundLight"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("BackgroundLight");
                }
                return _backgroundLight;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _black;
        /// <summary>
        /// Color resource: Black (Black)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color Black
        {
            get
            {
                if (_black == null)
                {
                    _black = Microsoft.Maui.Controls.Application.Current?.Resources["Black"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("Black");
                }
                return _black;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _cardDark;
        /// <summary>
        /// Color resource: CardDark (#2C2C2C)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color CardDark
        {
            get
            {
                if (_cardDark == null)
                {
                    _cardDark = Microsoft.Maui.Controls.Application.Current?.Resources["CardDark"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("CardDark");
                }
                return _cardDark;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _cardLight;
        /// <summary>
        /// Color resource: CardLight (#FFFFFF)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color CardLight
        {
            get
            {
                if (_cardLight == null)
                {
                    _cardLight = Microsoft.Maui.Controls.Application.Current?.Resources["CardLight"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("CardLight");
                }
                return _cardLight;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _primaryDark;
        /// <summary>
        /// Color resource: PrimaryDark (#66BB6A)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color PrimaryDark
        {
            get
            {
                if (_primaryDark == null)
                {
                    _primaryDark = Microsoft.Maui.Controls.Application.Current?.Resources["PrimaryDark"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("PrimaryDark");
                }
                return _primaryDark;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _primaryDarkDark;
        /// <summary>
        /// Color resource: PrimaryDarkDark (#81C784)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color PrimaryDarkDark
        {
            get
            {
                if (_primaryDarkDark == null)
                {
                    _primaryDarkDark = Microsoft.Maui.Controls.Application.Current?.Resources["PrimaryDarkDark"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("PrimaryDarkDark");
                }
                return _primaryDarkDark;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _primaryDarkLight;
        /// <summary>
        /// Color resource: PrimaryDarkLight (#1B5E20)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color PrimaryDarkLight
        {
            get
            {
                if (_primaryDarkLight == null)
                {
                    _primaryDarkLight = Microsoft.Maui.Controls.Application.Current?.Resources["PrimaryDarkLight"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("PrimaryDarkLight");
                }
                return _primaryDarkLight;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _primaryLight;
        /// <summary>
        /// Color resource: PrimaryLight (#2E7D32)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color PrimaryLight
        {
            get
            {
                if (_primaryLight == null)
                {
                    _primaryLight = Microsoft.Maui.Controls.Application.Current?.Resources["PrimaryLight"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("PrimaryLight");
                }
                return _primaryLight;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _secondaryDark;
        /// <summary>
        /// Color resource: SecondaryDark (#388E3C)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color SecondaryDark
        {
            get
            {
                if (_secondaryDark == null)
                {
                    _secondaryDark = Microsoft.Maui.Controls.Application.Current?.Resources["SecondaryDark"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("SecondaryDark");
                }
                return _secondaryDark;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _secondaryLight;
        /// <summary>
        /// Color resource: SecondaryLight (#81C784)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color SecondaryLight
        {
            get
            {
                if (_secondaryLight == null)
                {
                    _secondaryLight = Microsoft.Maui.Controls.Application.Current?.Resources["SecondaryLight"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("SecondaryLight");
                }
                return _secondaryLight;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _surfaceDark;
        /// <summary>
        /// Color resource: SurfaceDark (#1E1E1E)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color SurfaceDark
        {
            get
            {
                if (_surfaceDark == null)
                {
                    _surfaceDark = Microsoft.Maui.Controls.Application.Current?.Resources["SurfaceDark"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("SurfaceDark");
                }
                return _surfaceDark;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _surfaceLight;
        /// <summary>
        /// Color resource: SurfaceLight (#F5F5F5)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color SurfaceLight
        {
            get
            {
                if (_surfaceLight == null)
                {
                    _surfaceLight = Microsoft.Maui.Controls.Application.Current?.Resources["SurfaceLight"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("SurfaceLight");
                }
                return _surfaceLight;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _tertiaryDark;
        /// <summary>
        /// Color resource: TertiaryDark (#2E7D32)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color TertiaryDark
        {
            get
            {
                if (_tertiaryDark == null)
                {
                    _tertiaryDark = Microsoft.Maui.Controls.Application.Current?.Resources["TertiaryDark"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("TertiaryDark");
                }
                return _tertiaryDark;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _tertiaryLight;
        /// <summary>
        /// Color resource: TertiaryLight (#A5D6A7)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color TertiaryLight
        {
            get
            {
                if (_tertiaryLight == null)
                {
                    _tertiaryLight = Microsoft.Maui.Controls.Application.Current?.Resources["TertiaryLight"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("TertiaryLight");
                }
                return _tertiaryLight;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _textPrimaryDark;
        /// <summary>
        /// Color resource: TextPrimaryDark (#FFFFFF)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color TextPrimaryDark
        {
            get
            {
                if (_textPrimaryDark == null)
                {
                    _textPrimaryDark = Microsoft.Maui.Controls.Application.Current?.Resources["TextPrimaryDark"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("TextPrimaryDark");
                }
                return _textPrimaryDark;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _textPrimaryLight;
        /// <summary>
        /// Color resource: TextPrimaryLight (#212121)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color TextPrimaryLight
        {
            get
            {
                if (_textPrimaryLight == null)
                {
                    _textPrimaryLight = Microsoft.Maui.Controls.Application.Current?.Resources["TextPrimaryLight"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("TextPrimaryLight");
                }
                return _textPrimaryLight;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _textSecondaryDark;
        /// <summary>
        /// Color resource: TextSecondaryDark (#B0B0B0)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color TextSecondaryDark
        {
            get
            {
                if (_textSecondaryDark == null)
                {
                    _textSecondaryDark = Microsoft.Maui.Controls.Application.Current?.Resources["TextSecondaryDark"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("TextSecondaryDark");
                }
                return _textSecondaryDark;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _textSecondaryLight;
        /// <summary>
        /// Color resource: TextSecondaryLight (#757575)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color TextSecondaryLight
        {
            get
            {
                if (_textSecondaryLight == null)
                {
                    _textSecondaryLight = Microsoft.Maui.Controls.Application.Current?.Resources["TextSecondaryLight"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("TextSecondaryLight");
                }
                return _textSecondaryLight;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _white;
        /// <summary>
        /// Color resource: White (White)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color White
        {
            get
            {
                if (_white == null)
                {
                    _white = Microsoft.Maui.Controls.Application.Current?.Resources["White"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("White");
                }
                return _white;
            }
        }

        #endregion

        #region Gray Scale Colors

        private static Microsoft.Maui.Graphics.Color? _gray100;
        /// <summary>
        /// Color resource: Gray100 (#F5F5F5)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color Gray100
        {
            get
            {
                if (_gray100 == null)
                {
                    _gray100 = Microsoft.Maui.Controls.Application.Current?.Resources["Gray100"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("Gray100");
                }
                return _gray100;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _gray200;
        /// <summary>
        /// Color resource: Gray200 (#EEEEEE)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color Gray200
        {
            get
            {
                if (_gray200 == null)
                {
                    _gray200 = Microsoft.Maui.Controls.Application.Current?.Resources["Gray200"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("Gray200");
                }
                return _gray200;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _gray300;
        /// <summary>
        /// Color resource: Gray300 (#E0E0E0)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color Gray300
        {
            get
            {
                if (_gray300 == null)
                {
                    _gray300 = Microsoft.Maui.Controls.Application.Current?.Resources["Gray300"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("Gray300");
                }
                return _gray300;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _gray400;
        /// <summary>
        /// Color resource: Gray400 (#BDBDBD)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color Gray400
        {
            get
            {
                if (_gray400 == null)
                {
                    _gray400 = Microsoft.Maui.Controls.Application.Current?.Resources["Gray400"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("Gray400");
                }
                return _gray400;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _gray500;
        /// <summary>
        /// Color resource: Gray500 (#9E9E9E)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color Gray500
        {
            get
            {
                if (_gray500 == null)
                {
                    _gray500 = Microsoft.Maui.Controls.Application.Current?.Resources["Gray500"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("Gray500");
                }
                return _gray500;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _gray600;
        /// <summary>
        /// Color resource: Gray600 (#757575)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color Gray600
        {
            get
            {
                if (_gray600 == null)
                {
                    _gray600 = Microsoft.Maui.Controls.Application.Current?.Resources["Gray600"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("Gray600");
                }
                return _gray600;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _gray700;
        /// <summary>
        /// Color resource: Gray700 (#616161)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color Gray700
        {
            get
            {
                if (_gray700 == null)
                {
                    _gray700 = Microsoft.Maui.Controls.Application.Current?.Resources["Gray700"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("Gray700");
                }
                return _gray700;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _gray800;
        /// <summary>
        /// Color resource: Gray800 (#424242)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color Gray800
        {
            get
            {
                if (_gray800 == null)
                {
                    _gray800 = Microsoft.Maui.Controls.Application.Current?.Resources["Gray800"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("Gray800");
                }
                return _gray800;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _gray900;
        /// <summary>
        /// Color resource: Gray900 (#212121)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color Gray900
        {
            get
            {
                if (_gray900 == null)
                {
                    _gray900 = Microsoft.Maui.Controls.Application.Current?.Resources["Gray900"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("Gray900");
                }
                return _gray900;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _gray950;
        /// <summary>
        /// Color resource: Gray950 (#141414)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color Gray950
        {
            get
            {
                if (_gray950 == null)
                {
                    _gray950 = Microsoft.Maui.Controls.Application.Current?.Resources["Gray950"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("Gray950");
                }
                return _gray950;
            }
        }

        #endregion

        #region Accent Colors

        private static Microsoft.Maui.Graphics.Color? _accentDark;
        /// <summary>
        /// Color resource: AccentDark (#4CAF50)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color AccentDark
        {
            get
            {
                if (_accentDark == null)
                {
                    _accentDark = Microsoft.Maui.Controls.Application.Current?.Resources["AccentDark"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("AccentDark");
                }
                return _accentDark;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _accentLight;
        /// <summary>
        /// Color resource: AccentLight (#4CAF50)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color AccentLight
        {
            get
            {
                if (_accentLight == null)
                {
                    _accentLight = Microsoft.Maui.Controls.Application.Current?.Resources["AccentLight"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("AccentLight");
                }
                return _accentLight;
            }
        }

        #endregion

    }

    /// <summary>
    /// Fluent extension methods for working with colors
    /// </summary>
    public static class ColorExtensions
    {
        /// <summary>
        /// Creates a new color with the specified alpha/opacity value (0.0 to 1.0)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color WithAlpha(this Microsoft.Maui.Graphics.Color color, float alpha)
        {
            return color.WithAlpha(System.Math.Clamp(alpha, 0f, 1f));
        }

        /// <summary>
        /// Creates a new color with the specified opacity percentage (0 to 100)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color WithOpacity(this Microsoft.Maui.Graphics.Color color, int percentage)
        {
            return color.WithAlpha(System.Math.Clamp(percentage / 100f, 0f, 1f));
        }

        /// <summary>
        /// Creates a lighter version of the color
        /// </summary>
        /// <param name="factor">Amount to lighten (0.0 to 1.0, default 0.2)</param>
        public static Microsoft.Maui.Graphics.Color Lighten(this Microsoft.Maui.Graphics.Color color, float factor = 0.2f)
        {
            factor = System.Math.Clamp(factor, 0f, 1f);
            return new Microsoft.Maui.Graphics.Color(
                color.Red + (1 - color.Red) * factor,
                color.Green + (1 - color.Green) * factor,
                color.Blue + (1 - color.Blue) * factor,
                color.Alpha);
        }

        /// <summary>
        /// Creates a darker version of the color
        /// </summary>
        /// <param name="factor">Amount to darken (0.0 to 1.0, default 0.2)</param>
        public static Microsoft.Maui.Graphics.Color Darken(this Microsoft.Maui.Graphics.Color color, float factor = 0.2f)
        {
            factor = System.Math.Clamp(factor, 0f, 1f);
            return new Microsoft.Maui.Graphics.Color(
                color.Red * (1 - factor),
                color.Green * (1 - factor),
                color.Blue * (1 - factor),
                color.Alpha);
        }

        /// <summary>
        /// Converts the color to a hex string (e.g., #FF5733)
        /// </summary>
        public static string ToHex(this Microsoft.Maui.Graphics.Color color)
        {
            return $"#{(int)(color.Red * 255):X2}{(int)(color.Green * 255):X2}{(int)(color.Blue * 255):X2}";
        }

        /// <summary>
        /// Converts the color to a hex string with alpha (e.g., #FF5733AA)
        /// </summary>
        public static string ToHexWithAlpha(this Microsoft.Maui.Graphics.Color color)
        {
            return $"#{(int)(color.Red * 255):X2}{(int)(color.Green * 255):X2}{(int)(color.Blue * 255):X2}{(int)(color.Alpha * 255):X2}";
        }

        /// <summary>
        /// Creates a Color from a hex string. Supports formats: #RGB, #RRGGBB, #AARRGGBB, RGB, RRGGBB, AARRGGBB
        /// </summary>
        /// <param name="hex">Hex color string with or without #</param>
        public static Microsoft.Maui.Graphics.Color FromHex(string hex)
        {
            if (string.IsNullOrWhiteSpace(hex))
                throw new System.ArgumentException("Hex string cannot be null or empty", nameof(hex));

            hex = hex.Trim().TrimStart('#');

            // Handle 3-digit shorthand (e.g., "RGB" -> "RRGGBB")
            if (hex.Length == 3)
                hex = $"{hex[0]}{hex[0]}{hex[1]}{hex[1]}{hex[2]}{hex[2]}";

            int alpha = 255;
            int red, green, blue;

            if (hex.Length == 6)
            {
                // RRGGBB
                red = System.Convert.ToInt32(hex.Substring(0, 2), 16);
                green = System.Convert.ToInt32(hex.Substring(2, 2), 16);
                blue = System.Convert.ToInt32(hex.Substring(4, 2), 16);
            }
            else if (hex.Length == 8)
            {
                // AARRGGBB
                alpha = System.Convert.ToInt32(hex.Substring(0, 2), 16);
                red = System.Convert.ToInt32(hex.Substring(2, 2), 16);
                green = System.Convert.ToInt32(hex.Substring(4, 2), 16);
                blue = System.Convert.ToInt32(hex.Substring(6, 2), 16);
            }
            else
            {
                throw new System.ArgumentException($"Invalid hex color format: {hex}. Expected 3, 6, or 8 characters.", nameof(hex));
            }

            return new Microsoft.Maui.Graphics.Color(red / 255f, green / 255f, blue / 255f, alpha / 255f);
        }

        /// <summary>
        /// Creates a Color from RGBA hex string. Supports formats: #RRGGBBAA, RRGGBBAA
        /// </summary>
        /// <param name="hex">RGBA hex color string with or without #</param>
        public static Microsoft.Maui.Graphics.Color FromHexRGBA(string hex)
        {
            if (string.IsNullOrWhiteSpace(hex))
                throw new System.ArgumentException("Hex string cannot be null or empty", nameof(hex));

            hex = hex.Trim().TrimStart('#');

            if (hex.Length != 8)
                throw new System.ArgumentException($"Invalid RGBA hex format: {hex}. Expected 8 characters (RRGGBBAA).", nameof(hex));

            int red = System.Convert.ToInt32(hex.Substring(0, 2), 16);
            int green = System.Convert.ToInt32(hex.Substring(2, 2), 16);
            int blue = System.Convert.ToInt32(hex.Substring(4, 2), 16);
            int alpha = System.Convert.ToInt32(hex.Substring(6, 2), 16);

            return new Microsoft.Maui.Graphics.Color(red / 255f, green / 255f, blue / 255f, alpha / 255f);
        }
    }
}
